blank_issues_enabled: false
contact_links:
  - name: Discussion / question générale
    url: ../discussions
    about: Pour les questions ouvertes ou les suggestions qui ne rentrent pas dans une issue.
